[modules.digipos]
name = "digipos"
base_url = "http://10.0.0.3:10003"
method = "GET"
timeout = 10
max_retries = 3
seconds_between_retries = 3
replace_with_regex = true
list_regex_replacement = ["\\b(DAYS?|HARI)\\b", "(\\d+)\\s*GB", "(\\d+)\\s*D", "\\bINTERNET\\b"]
exclude_product = true
list_prefixes = ["Facebook"]

[modules.tsel]
name = "tsel"
base_url = "http://10.0.0.4:10004"
method = "POST"
timeout = 8
max_retries = 2
seconds_between_retries = 2
replace_with_regex = false
list_regex_replacement = []
exclude_product = false
list_prefixes = []
